name: NodeJS with Grunt

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Test
    steps:
    - uses: actions/checkout@v2
    
    - name: Find and Replace Full Name
      uses: jacobtomlinson/gha-find-replace@2.0.0
      with:
        include: '**/index.html'
        find: $FullName
        replace: 'Test Test'
        regex: false
        
    - name: Find and Replace Full Name
      uses: jacobtomlinson/gha-find-replace@2.0.0
      with:
        include: '**/index.html'
        find: $PhoneNumber
        replace: '+000 00 000 00 00'
        regex: false
  
    - name: FTP Deploy to Fornex
      # You may pin to the exact commit or the version.
      # uses: SamKirkland/FTP-Deploy-Action@65c6a8f943bbf04faf9b59520a103318b418952e
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        # ftp server
        server: ${{ secrets.FTP_SERVER_NAME }}
        # ftp username
        username: ${{ secrets.FTP_USER_NAME }}
        # ftp password
        password: ${{ secrets.FTP_USER_PASSWORD }}
        # Server port to connect to (read your web hosts docs)
        port: ${{ secrets.FTP_SERVER_PORT }}
        # protocol to deploy with - ftp, ftps, or ftps-legacy
        protocol: ftps
        # Folder to upload from, must end with trailing slash /
        local-dir: 'src/'
        # Path to upload to on the server. Must end with trailing slash /
        server-dir: 'public_html/'
        # Path and name of the state file - this file is used to track which files have been deployed
        # An array of glob patterns, these files will not be included in the publish/delete process
        exclude: '*.yaml'
        # How verbose should the information be - minimal, standard, or verbose
        log-level: standard
        # strict or loose
        security: loose
    
